=== tarunjais28/provenance-token-contract/schema/raw/instantiate.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "InstantiateMsg",
  "type": "object",
  "required": [
    "bal_cap",
    "decimals",
    "frozen_balances",
    "initial_balances",
    "name",
    "symbol"
  ],
  "properties": {
    "bal_cap": {
      "description": "balance cap for each token holder (eg. balance cap for each user = 1000, users can only hold up to 1000 tokens.",
      "allOf": [
        {
          "$ref": "#/definitions/Uint128"
        }
      ]
    },
    "decimals": {
      "description": "decimal places of the derivative token (for UI)",
      "type": "integer",
      "format": "uint8",
      "minimum": 0.0
    },
    "frozen_balances": {
      "description": "frozen balance",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Cw20Coin"
      }
    },
    "initial_balances": {
      "description": "initial balance",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Cw20Coin"
      }
    },
    "mint": {
      "description": "minting data",
      "anyOf": [
        {
          "$ref": "#/definitions/MinterResponse"
        },
        {
          "type": "null"
        }
      ]
    },
    "name": {
      "description": "name of the derivative token",
      "type": "string"
    },
    "symbol": {
      "description": "symbol / ticker of the derivative token",
      "type": "string"
    }
  },
  "definitions": {
    "Cw20Coin": {
      "type": "object",
      "required": [
        "address",
        "amount"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "amount": {
          "$ref": "#/definitions/Uint128"
        }
      }
    },
    "MinterResponse": {
      "type": "object",
      "required": [
        "minter"
      ],
      "properties": {
        "cap": {
          "description": "cap is a hard cap on total supply that can be achieved by minting. Note that this refers to total_supply. If None, there is unlimited cap.",
          "anyOf": [
            {
              "$ref": "#/definitions/Uint128"
            },
            {
              "type": "null"
            }
          ]
        },
        "minter": {
          "type": "string"
        }
      }
    },
    "Uint128": {
      "description": "A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.\n\n# Examples\n\nUse `from` to create instances of this and `u128` to get the value out:\n\n``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);\n\nlet b = Uint128::from(42u64); assert_eq!(b.u128(), 42);\n\nlet c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ```",
      "type": "string"
    }
  }
}

=== tarunjais28/provenance-token-contract/contracts/cw20-contract/parameters/init.json
{
    "name": "Bash Shell",
    "symbol": "BASH",
    "decimals": 6,
    "initial_balances": [
        {
            "address": "tp1lz7rw3p48tsztjaqpnqzz7vzwfczrlkcrwkgqy",
            "amount": "500"
        },
        {
            "address": "tp1m97r57ms8dl7pxn0j4m7w80d6a5qvdp7pns80g",
            "amount": "250"
        }
    ],
    "frozen_balances": [
        {
            "address": "tp1lz7rw3p48tsztjaqpnqzz7vzwfczrlkcrwkgqy",
            "amount": "400"
        }
    ],
    "mint": {
        "minter": "tp1c7apkgl4l8pw72nsh6uvvr7d6fy3c98hyg0sct",
        "cap": "2000"
    },
    "bal_cap": "1000"
}
